
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: '桂电校园网掉线自连'
          options: --onefile, --name "桂电校园网掉线自连", --windowed, 